#key=value pairs
# for extension point="dreisoft.tresos.launcher2.plugin.module"
module.id=com.continental.ibs.swp.Pfm.1.0.0
module.label=Pfm
module.ext.id=com.continental.ibs.swp.Pfm.module.id..1.0.0
module.ext.name=Pfm Module
# Human readable description
module.description=Continental Pfm Module

# Name of the module
module.name=Pfm

module.cluster.name=SWP

module.category=Driver
module.category.layer=Service
module.category.component=ECUC

# for extension point="dreisoft.tresos.launcher2.plugin.configuration"
module.configuration.ext.id=com.continental.ibs.swp.Pfm.configuration.1.0.0
module.configuration.ext.name=Pfm Configuration Extension
module.configuration.xdm.id=com.continental.ibs.swp.Pfm.configuration.id
module.configuration.xdm=config/Pfm.xdm
module.configuration.aspath=ASPath:/SWP/Pfm
module.editor.id=com.continental.ibs.swp.Pfm.module.editor.id.1.0.0

# for extension point="dreisoft.tresos.launcher2.plugin.generator"
module.generator.name=Pfm Template Generator Extension
module.generator.id=com.continental.ibs.swp.Pfm.generator.1.0.0
module.generator.int.id=com.continental.ibs.swp.Pfm.template.generator.1.0.0
